# Generated by Django 4.0.5 on 2022-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
